### ISSUE TITLE
Any chance to get a documentation?

### ISSUE THREAD

**Issue by c0pper** [Codestian/MqttCraft#1]
Hi I'm on the lookout for something that adds mqtt to minecraft, any chance to get a documentation for this mod? Thanks

**Comment by Codestian** [comment]
Hello, I will be documenting it soon but you can check out the contents of Action.java and Trigger.java for the topic names. By default topicPrefix is "minecraft".
As an example, mqttcraft updates the player's health to the topic "minecraft/trigger/player/health" everytime it changes, and you can use an mqtt client like Mosquitto to subscribe to it.
